// file: SubastaOntology.java generated by ontology bean generator.  DO NOT EDIT, UNLESS YOU ARE REALLY SURE WHAT YOU ARE DOING!
package ontologia;

import jade.content.onto.*;
import jade.content.schema.*;

/** file: SubastaOntology.java
 * @author OntologyBeanGenerator v4.1
 * @version 2021/12/24, 12:37:29
 */
public class SubastaOntology extends jade.content.onto.Ontology  {

  private static final long serialVersionUID = 7915611569178847533L;

  //NAME
  public static final String ONTOLOGY_NAME = "Subasta";
  // The singleton instance of this ontology
  private static Ontology theInstance = new SubastaOntology();
  public static Ontology getInstance() {
     return theInstance;
  }


   // VOCABULARY
    public static final String GANAR_GANADOR="ganador";
    public static final String GANAR_PUJA="puja";
    public static final String GANAR="Ganar";
    public static final String OFERTAR_OFERTA="oferta";
    public static final String OFERTAR="Ofertar";
    public static final String RESPONDER_PARTICIPO="participo";
    public static final String RESPONDER="Responder";
    public static final String LIBRO_TITULO="Titulo";
    public static final String LIBRO_ID="id";
    public static final String LIBRO="Libro";
    public static final String OFERTA_PRECIO="precio";
    public static final String OFERTA_PRODUCTO="producto";
    public static final String OFERTA="Oferta";

  /**
   * Constructor
  */
  private SubastaOntology(){ 
    super(ONTOLOGY_NAME, BasicOntology.getInstance());
    try { 

    // adding Concept(s)
    ConceptSchema ofertaSchema = new ConceptSchema(OFERTA);
    add(ofertaSchema, ontologia.Oferta.class);
    ConceptSchema libroSchema = new ConceptSchema(LIBRO);
    add(libroSchema, ontologia.Libro.class);

    // adding AgentAction(s)
    AgentActionSchema responderSchema = new AgentActionSchema(RESPONDER);
    add(responderSchema, ontologia.Responder.class);
    AgentActionSchema ofertarSchema = new AgentActionSchema(OFERTAR);
    add(ofertarSchema, ontologia.Ofertar.class);

    // adding AID(s)

    // adding Predicate(s)
    PredicateSchema ganarSchema = new PredicateSchema(GANAR);
    add(ganarSchema, ontologia.Ganar.class);


    // adding fields
    ofertaSchema.add(OFERTA_PRODUCTO, libroSchema, ObjectSchema.MANDATORY);
    ofertaSchema.add(OFERTA_PRECIO, (TermSchema)getSchema(BasicOntology.INTEGER), ObjectSchema.MANDATORY);
    libroSchema.add(LIBRO_ID, (TermSchema)getSchema(BasicOntology.INTEGER), ObjectSchema.MANDATORY);
    libroSchema.add(LIBRO_TITULO, (TermSchema)getSchema(BasicOntology.STRING), ObjectSchema.MANDATORY);
    responderSchema.add(RESPONDER_PARTICIPO, (TermSchema)getSchema(BasicOntology.BOOLEAN), ObjectSchema.MANDATORY);
    ofertarSchema.add(OFERTAR_OFERTA, ofertaSchema, ObjectSchema.MANDATORY);
    ganarSchema.add(GANAR_PUJA, ofertaSchema, ObjectSchema.MANDATORY);
    ganarSchema.add(GANAR_GANADOR, (TermSchema)getSchema(BasicOntology.STRING), ObjectSchema.MANDATORY);

    // adding name mappings

    // adding inheritance

   }catch (java.lang.Exception e) {e.printStackTrace();}
  }
}
